//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketIllusions.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Illusions
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int IllusionistId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<int> TargetUserId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
