//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketIllusions.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Illusions = new HashSet<Illusions>();
            this.Illusions1 = new HashSet<Illusions>();
            this.Orders = new HashSet<Orders>();
            this.ProductHistory = new HashSet<ProductHistory>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string AvatarPath { get; set; }
        public Nullable<int> SuggestibilityLevel { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual ICollection<Illusions> Illusions { get; set; }
        public virtual ICollection<Illusions> Illusions1 { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<ProductHistory> ProductHistory { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
